"""Add verification_token column to Users table

Revision ID: 730f69519695
Revises: 
Create Date: 2024-08-01 23:39:56.302324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '730f69519695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users_creds', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('is_verified',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users_creds', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=11, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    # ### end Alembic commands ###
