"""change the size of  verification_token column 

Revision ID: 91a92a8f894e
Revises: 
Create Date: 2024-08-02 23:31:30.470941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '91a92a8f894e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users_creds', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users_creds', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###
